version: "3.9"
services:
  web:
    restart: always
    build: 
      context: .
      dockerfile: Dockerfile
    env_file: ./.env
    command: yarn start
    ports: 
      - $NODE_LOCAL_PORT:$NODE_DOCKER_PORT
    volumes:
      - ./:/src/
    depends_on:
      - mysqldb
    environment:
      MYSQL_HOST: mysqldb
  mysqldb:
    image: mysql
    ports:
      - $MYSQL_LOCAL_PORT:$MYSQL_DOCKER_PORT
    volumes:
      - mysql:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: $MYSQL_ROOT_PASSWORD
      MYSQL_DATABASE: $MYSQL_DATABASE
   

volumes:
  mysql:
  mysqlconfig:

